'use client';
import Head from "next/head";
import React, { useState, useEffect } from 'react';
import map from "/public/RECON1_FIT_data.json";
import model from "/public/PPPmodel.json";
import dynamic from "next/dynamic";

const DynamicEscherMap = dynamic(() => import("../components/EscherMap"), {ssr: false});

export default function Home() {
  const [reactionData, setReactionData] = useState(null);
  const [descriptor, setDescriptor] = useState('All_IDopa');

  const fetchData = async (descriptor) => {
    const url = `/api/getFlightInfo?descriptor=${encodeURIComponent(descriptor)}`;

    try{
      // Fetch data from the Flight_RPC server
      const res = await fetch(url)

      const data = await res.json();
      console.log(data, 'data');
      setReactionData(data);
    }catch (e) {
      console.error(e);
    }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1>VMH</h1>
        <div className="header">
          <h2>mock VMH tabs</h2>
          <div style={{
            padding: '20px',
            background: '#f0f0f0',
            borderRadius: '8px',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            maxWidth: '400px',
            margin: 'auto'
          }}>
            <input
              type="text"
              value={descriptor}
              onChange={(e) => {
                console.log(e.target.value, 'e.target.value');
                setDescriptor(e.target.value);
              }}
              style={{padding: '10px', width: '70%', borderRadius: '4px', border: '1px solid #ccc'}}
            />
            <button
              onClick={() => fetchData(descriptor)}
              style={{
                padding: '10px 20px',
                borderRadius: '4px',
                backgroundColor: '#007bff',
                color: 'white',
                border: 'none',
                cursor: 'pointer'
              }}
            >
              Fetch Data
            </button>
          </div>
          <p>Escher Next is a Next.js app that uses the Escher library to display a metabolic map. This example uses the
            RECON1_FIT_data.json map and the PPPmodel.json model.</p>
        </div>
        <DynamicEscherMap map={map} model={model} reactionData={reactionData}/>
      </div>
    </>
  );
}
