'use client';
import Head from "next/head";
import map from "/public/RECON1_FIT_data.json";
import model from "/public/PPPmodel.json";
import dynamic from "next/dynamic";

const DynamicEscherMap = dynamic(() => import("../components/EscherMap"), {ssr: false});

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1>VMH</h1>
        <div className="header">
          <h2>mock VMH tabs</h2>
          <p>Escher Next is a Next.js app that uses the Escher library to display a metabolic map. This example uses the RECON1_FIT_data.json map and the PPPmodel.json model.</p>
        </div>
        <DynamicEscherMap map={map} model={model} />
      </div>
    </>
  );
}
